--liquibase formatted sql

--changeset AM: table_animal_shelter.sql

CREATE TABLE users
(
    id                      bigint generated by default as identity primary key,
    chat_id                 bigint not null,
    name                    text not null,
    is_dog                  BOOLEAN NOT NULL
);