--liquibase formatted sql

--changeset AM : create_table_animal_shelter.sql

CREATE TABLE users
(
    id                      bigint generated by default as identity primary key,
    chat_id                 bigint not null,
    name                    text not null,
    is_dog                  BOOLEAN NOT NULL
);

CREATE TABLE dog
(
    id                      bigint generated by default as identity primary key,
    name                    text not null,
    age                     integer,
    breed                   text not null
);


CREATE TABLE owner_dog
(
    id                      bigint generated by default as identity primary key,
    chat_id                 bigint not null,
    name                    text not null,
    phone                   text not null,
    age                     integer,
    dog_id                  bigint references dog(id),
    number_of_report_days   bigint
);
